apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: k8s-myapp-sa
      containers:
      - name: my-app
        image: us-east4-docker.pkg.dev/projectid/my-repository/restfulapp:latest
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: -Xms256m -Xmx512m -server -XX:MaxHeapFreeRatio=40 -XX:MinHeapFreeRatio=30
        ports:
          - containerPort: 8080